_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1
max_epochs: 30

accelerator: gpu
devices: 1

precision: 16

check_val_every_n_epoch: 1
log_every_n_steps: 10

# makes training slower but gives more reproducibility than just setting seeds
deterministic: False