docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    # Main image
    - docker build --pull -t "$DOCKER_IMAGE_NAME" -f dockerfiles/Dockerfile .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi

    # Dashboard image
    - DASHBOARD_IMAGE_NAME="$CI_REGISTRY_IMAGE:dashboard-$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$DASHBOARD_IMAGE_NAME" -f dockerfiles/Dockerfile.dashboard .
    - docker push "$DASHBOARD_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DASHBOARD_IMAGE_NAME" "$CI_REGISTRY_IMAGE:dashboard-latest"
        docker push "$CI_REGISTRY_IMAGE:dashboard-latest"
      fi

  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - dockerfiles/Dockerfile
        - dockerfiles/Dockerfile.dashboard