version: '3.8'

services:
  influxdb:
    image: influxdb:2.6-alpine
    hostname: influxdb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
      - influxdb_config:/etc/influxdb2:rw
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}

  preprocessing:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
    depends_on:
      - influxdb

  filebrowser:
    image: filebrowser/filebrowser
    restart: unless-stopped
    volumes:
      - ./data:/srv
    ports:
      - "8080:80"

volumes:
  influxdbv2:
  influxdb_config:
  filebrowserdb:
  filebrowserconfig: