_target_: src.models.xlstm.x_lstm.xLSTM
num_layers: 3
signature: [2, 1]
inp_dim: 16
head_dim: 32
head_num: 4
output_size: 5
p_factor: [2, 4/3]
ker_size: 4

optimizer:
  _target_: torch.optim.AdamW # Changed from Adam to AdamW as described in the paper https://arxiv.org/pdf/2405.04517
  _partial_: true
  lr: 0.001
  weight_decay: 0.1 # as described in the paper https://arxiv.org/pdf/2405.04517 which is not a recommendation but a suggestion
