# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  anonymous: null
  project: "lightning-hydra-template"
  log_model: True # upload lightning ckpts
  entity: "" # set to name of your wandb team
  group: ""
  tags: [ ]
  job_type: ""