defaults:
  - _self_
  - data: sensor
  - database: default
  - preprocessing: default
  - partitioning: default
  - paths: default

  - trainer: null
  - model: null # Added to enable override in experiment config
  - experiment: null

n_jobs: null
verbose: true
seed: 1337