defaults:
  - _self_
  - paths: default
  - partitioning: default
  - preprocessing: default
  - model: log_reg
  - data: sensor
  - trainer: gpu

  - experiment: null

refit_on_all_data: False
ckpt_path: null
seed: 1337