defaults:
  - _self_
  - paths: default
  - partitioning: default
  - preprocessing: default
  - model: deep_res_bidir_lstm
  - data: sensor
  - trainer: mps

  - experiment: null

ckpt_path: null
seed: 1337